name: listen
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: 1 0 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run install
      - run: npm run listen
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERID: ${{ secrets.USERID }}
